services:
  app: &base
    platform: linux/amd64
    build:
      context: .
    image: keboola/ex-db-snowflake
    environment:
      - KBC_COMPONENT_RUN_MODE
      - KBC_RUNID
      - KBC_DATA_TYPE_SUPPORT=none
      - SNOWFLAKE_DB_HOST
      - SNOWFLAKE_DB_PORT
      - SNOWFLAKE_DB_USER
      - SNOWFLAKE_DB_PASSWORD
      - SNOWFLAKE_DB_DATABASE
      - SNOWFLAKE_DB_SCHEMA
      - SNOWFLAKE_DB_WAREHOUSE
      - SNOWFLAKE_DB_ROLE_NAME
      - SNOWFLAKE_DB_PRIVATE_KEY

  dev:
    <<: *base
    volumes:
      - .:/code
      - ./data:/data
